miu タイプミスでも回答アップロードするバグを修正

diff --git a/miu b/miu
--- a/miu
+++ b/miu
@@ -4,6 +4,11 @@ HostPort=80
 PlayerID="308685860"
 ProblemNumber="0"
 
+if [ $# -ne 1 ]; then
+	echo "./miu (c|g|1|filename)"
+	exit 1;
+fi
+
 case $1 in
 # PlayerID確認
 	"c")
@@ -22,6 +27,10 @@ case $1 in
 	;;
 # 回答提出　パラメータは回答ファイル名
 	*)
-		wget -qO - --post-file=$1 http://$HostName:$HostPort/SubmitAnswer?PlayerID=$PlayerID\&ProblemNumber=$ProblemNumber
+		if [ -e $1 ]; then
+			wget -qO - --post-file=$1 http://$HostName:$HostPort/SubmitAnswer?PlayerID=$PlayerID\&ProblemNumber=$ProblemNumber
+		else
+			echo 'file not found'
+		fi
 	;;
 esac
